name: deploy to production

on:
  push:
    tags:
      - 'v*'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_api_name: "test-tag-release"
          heroku_email: "osantos@intellisys.com.do"